<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" />
    <PackageReference Include="FreeSpire.Doc" />
    <PackageReference Include="FreeSpire.Presentation" />
    <PackageReference Include="jieba.NET" />
    <PackageReference Include="LlmTornado" />
    <PackageReference Include="LlmTornado.Agents" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Onnx" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\external\AquaAvgFramework\AquaAvgFramework.csproj" />
    <ProjectReference Include="..\ReciteHelper.Core\ReciteHelper.Core.csproj" />
  </ItemGroup>

</Project>
